### ISSUE TITLE
query运行不起来

### ISSUE THREAD

**Issue by marsws** [blahgeek/toefl-neea-checker#1]
query 考位那里获取不成功，需要手动点一下？

**Comment by blahgeek** [comment]
理应不需要。观察一下chrome上页面跳转的情况吧，看是卡在哪一步了

**Comment by blahgeek** [comment]
改一下代码里的日期和地点？默认的日期已经过了

**Comment by marsws** [comment]
改过了日期时间哦，没用，query那里 他好像是没有点击操作，不太熟悉selenium

**Comment by blahgeek** [comment]
搞明白了，网站似乎增加了鼠标移动的检测（给跪了），代码已经更新。
